- import_playbook: step1.yml

- hosts: undercloud
  gather_facts: false
  become: true
  become_user: stack
  tags: undercloud_install
  tasks:
    - name: run undercloud install
      command: >-
        script -c 'openstack undercloud install' undercloud-install.log
      args:
        chdir: /home/stack

- import_playbook: step2.yml
- import_playbook: step3.yml
- import_playbook: step4.yml

- hosts: undercloud
  gather_facts: false
  become: true
  become_user: stack
  tags: overcloud_install
  tasks:
    - name: run overcloud install
      shell: |
        pwd
        . ./stackrc
        script -c 'sh overcloud-deploy.sh' overcloud-deploy.log
      args:
        chdir: /home/stack
