---
- name: ensure work directory exists
  hosts: virthost
  tags: [always]
  tasks:
    - name: ensure work directory is defined
      set_fact:
        osp_demo_workdir: "/tmp/director-install-tmp"
      when: osp_demo_workdir is not defined

    - name: ensure work directory exists
      file:
        path: "{{ osp_demo_workdir }}"
        state: directory

# Install and activate libvirt and openvswitch on your virtual host.
- name: prepare virthost
  hosts: virthost
  tags: [virthost]
  tasks:
    - name: ensure openvswitch is installed
      include_role:
        name: openvswitch

    - name: ensure libvirt is installed
      include_role:
        name: libvirt

    - name: ensure libvirt is configured
      include_role:
        name: libvirt
        tasks_from: configure.yml

# Generate the undercloud disk image and boot the undercloud.
- name: prepare undercloud guest
  tags: [create-undercloud]
  hosts: virthost
  gather_facts: false
  tasks:
    - name: configure undercloud image
      include_role:
        name: undercloud_image

    - name: create undercloud guest
      include_role:
        name: undercloud_guest

    - name: give inventory time to settle
      pause:
        seconds: 5

- name: refresh inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - meta: refresh_inventory

# Configure the undercloud, including registering it with 
# subscription-manager. After this task is complete you can run the
# `openstack undercloud install` command.
- hosts: undercloud
  name: configure undercloud
  tags: [configure-undercloud]
  tasks:
    - name: basic undercloud configuration
      include_role:
        name: undercloud_config

    - name: register undercloud
      tags: [register, extended]
      include_role:
        name: undercloud_register

    - name: ensure a functional version of podman is installed
      tags: [bugs]
      include_role:
        name: podman

    - name: prepare stack user
      include_role:
        name: stack_user

    - name: prepare undercloud install
      include_role:
        name: undercloud_install_prep
