---
libvirt_uri: "qemu:///system"

rhel_image:
  path: /var/tmp/rhel-8.1-x86_64-kvm.qcow2
  format: qcow2

undercloud_image_size: 100g

undercloud_keys:
  - https://github.com/larsks.keys

openstack_switch: openstack

redhat_repositories:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - rhel-8-for-x86_64-highavailability-rpms
  - ansible-2.8-for-rhel-8-x86_64-rpms
  - openstack-15-for-rhel-8-x86_64-rpms
  - fast-datapath-for-rhel-8-x86_64-rpms

overcloud_hosts:
  controller:
    name: controller
    count: "{{ controller_count|default(3) }}"
    ram: "{{ controller_ram|default(8000) }}"
    disk: "{{ controller_disk|default(50) }}"
    vcpus: "{{ controller_vcpus|default(4) }}"
    networks:
      - network=openstack,portgroup=internal,boot_order=1
      - network=default
      - network=openstack,portgroup=storage
      - network=openstack,portgroup=external
      - network=openstack,portgroup=floating
  compute:
    name: compute
    count: "{{ compute_count|default(2) }}"
    ram: "{{ compute_ram|default(8000) }}"
    disk: "{{ compute_disk|default(50) }}"
    vcpus: "{{ compute_vcpus|default(2) }}"
    networks:
      - network=openstack,portgroup=internal,boot_order=1
      - network=default
      - network=openstack,portgroup=storage
      - network=openstack,portgroup=external
      - network=openstack,portgroup=floating

os_flavors:
  - name: m1.tiny
    state: present
    ram: 513
    vcpus: 1
    disk: 10

os_projects:
  - demo

os_users:
  - name: demo
    password: demo
    default_project: demo

os_images:
  - name: centos-7-x86_64
    format: qcow2
    url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    properties:
      distro: centos

external_network_cidr: 10.0.0.0/24
floating_network_cidr: 10.1.0.0/24
