---
- name: check for iptables rule for virbr0
  command: iptables -C INPUT -i virbr0 -j ACCEPT
  register: virbr0_rule
  failed_when: false
  changed_when: virbr0_rule.rc != 0

- name: create iptables rule for virbr0
  command: iptables -I INPUT 1 -i virbr0 -j ACCEPT
  when: virbr0_rule is changed

- name: preserve iptables configuration
  shell: iptables-save > /etc/sysconfig/iptables
  when: virbr0_rule is changed

- name: install libvirt packages
  yum:
    enablerepo: delorean,delorean-train-testing,rdo-qemu-ev
    name: "{{ libvirt_packages }}"
    state: present

- name: activate libvirt service
  service:
    name: libvirtd
    state: started
    enabled: true

- name: activate virtualbmc service
  service:
    name: virtualbmc
    state: started
    enabled: true

- name: check if default pool is available
  command: >-
    virsh pool-info default
  register: default_pool
  failed_when: false
  changed_when: default_pool.rc != 0
  environment:
    LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"

- name: create default pool
  when: default_pool is changed
  block:
    - name: ensure images directory exists
      file:
        path: "{{ libvirt_default_pool_directory }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: define default pool
      command: >-
        virsh pool-define-as default
        --type dir
        --target "{{ libvirt_default_pool_directory }}"
      environment:
        LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"

    - name: start default pool
      command: >-
        virsh pool-start default
      environment:
        LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"

    - name: mark default pool for autostart
      command: >-
        virsh pool-autostart default
      environment:
        LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"
