---
- name: fetch base image
  get_url:
    url: "{{ base_image_url }}"
    dest: "{{ base_image_path }}"

- name: set undercloud_image_path fact
  set_fact:
    undercloud_image_path: "{{ osp_demo_workdir }}/undercloud.qcow2"

- name: create undercloud base image
  command: >-
    qemu-img create
    -b {{ base_image_path }}
    -F qcow2
    -f qcow2
    {{ undercloud_image_path }} {{ undercloud_image_size }}
  args:
    creates: "{{ undercloud_image_path }}"
  register: undercloud_image_create

- name: configure undercloud image
  when: undercloud_image_create is changed
  block:

    - name: fetch authorized keys
      command: >-
        curl -a -o {{ osp_demo_workdir }}/authorized_keys {{ item }}
      args:
        warn: false
      loop: "{{ undercloud_keys }}"

    - name: copy customization script to virthost
      copy:
        src: customize.sh
        dest: "{{ osp_demo_workdir }}/customize.sh"

    - name: configure undercloud base image
      command: >-
        virt-customize -a {{ undercloud_image_path }}
        --mkdir /root/.ssh \
        --upload {{ osp_demo_workdir }}/authorized_keys:/root/.ssh/authorized_keys
        --run {{ osp_demo_workdir }}/customize.sh
        --selinux-relabel

  rescue:

    - name: delete undercloud image
      file:
        path: "{{ undercloud_image_path }}"
        state: absent

    - fail:
