---
- name: check if overlcoud image exists in glance
  become: true
  become_user: stack
  shell: |-
    . $HOME/stackrc
    openstack image show overcloud-full
  register: image_check
  failed_when: false
  changed_when: image_check.rc != 0

- name: get overcloud images
  when: image_check is changed
  block:
    - name: create image fetch directory
      file:
        path: "{{ overcloud_image_download_directory }}"
        state: directory

    - name: fetch overcloud image packages
      get_url:
        url: "{{ item.url }}"
        dest: "{{ overcloud_image_download_directory }}/{{ item.name }}.tar"
      loop: "{{ overcloud_image_urls }}"

    - name: unpack overcloud images
      become: true
      become_user: stack
      shell: |-
        mkdir -p $HOME/images
        tar -C $HOME/images \
        -xf {{ overcloud_image_download_directory }}/{{ item.name }}.tar
      args:
        warn: false
      loop: "{{ overcloud_image_urls }}"

    - name: upload images to glance
      become: true
      become_user: stack
      shell: |-
        . $HOME/stackrc
        openstack overcloud image upload --image-path /home/stack/images/
